### ISSUE TITLE
Clarify which frameworks the package supports 

### ISSUE THREAD

**Issue by MNF** [mihirdilip/Mihir.AspNetCore.Authentication.Basic#7]
In the description it is said that the package can be used fro .Net core, but in details it is said that .NET Framework 4.6.1 is also supported. Please keep the title and content consistent.

Please add an example how to use with .Net framework 4.6.1.

Also fix the phrase “ Always use HTTPS (SSL Certificate) protocol in production when using API Key authentication.” as this repo is about basic authentication.

**Comment by mihirdilip** [comment]
@MNF , thanks for spotting the typo. I have now updated the readme to read basic authentication instead of API Key authentication.

Regarding the description, in case if you are not aware, ASP.NET Core and .NET Core completely separate. ASP.NET Core can be used on .NET Framework app as long as it confirms to netstandard2.0. I can give 2 simple examples where and how it can be used on .NET Framework.

1. If you were to create a Console project with a .NET Framework 4.6.1 or newer, you can use ASP.NET Core in the same way you would do on a netcoreapp project. 
2. Create a new or on your existing ASP.NET Core app, if you change the TargetFramework to net461 or newer, it will use the .NET Framework for your ASP.NET Core app.

Now since this library is for ASP.NET Core, the description is correct.

Once again, thanks for your feedback.
